### ISSUE TITLE
The view feature is not work when Review image content

### ISSUE THREAD

**Issue by Icramss** [Steemia/Steemia#75]
## Expected Behavior
After writing the content the user should be able to review it before posting

## Actual Behavior
View feature does not work
normally

## Steps to Reproduce the Problem

  1.launc app
  1.sign in with your steem account
  1.create a new post and write any text /image than Tap view icon 

## Specifications

  - Version: device 6.0.1

**Comment by jayserdny** [comment]
Hello,

Sorry, but I cannot reproduce this issue. Can you please attach a GIF or video reproducing this issue?

Thanks.

**Comment by Icramss** [comment]
Yap. This is my reproduce
![20180603_033443.gif](https://cdn.steemitimages.com/DQmPUkXthLvqYrV4MvTWSEL1KX6Pu6qFAJzgZaJpphwU28j/20180603_033443.gif)

**Comment by jayserdny** [comment]
@Icramss What version of the app are you using? I tried on my device and it is working properly.

**Comment by Icramss** [comment]
0.0.4 version

**Comment by jayserdny** [comment]
@Icramss and what is the device's model?

**Comment by Icramss** [comment]
One plus 2

**Comment by Icramss** [comment]
Get me a bug label if this is help you

**Comment by jayserdny** [comment]
Can you please confirm that other items in the toolbox work? @Icramss

**Comment by Icramss** [comment]
Yes . All item in toolbox work except View

**Comment by Icramss** [comment]
Please try this way:

Write little content and upload images. Once the image has finished uploading, try Review. Maybe this way can help you in knowing the cause

**Comment by jayserdny** [comment]
It worked for me but since others items are working, I will mark it as bug

**Comment by Icramss** [comment]
Yep. I will change the title of the issue with the behavior you can produce.

**Comment by tobias-g1** [comment]
Interestingly I was able to replicate this too, on both Android 8.0, 7.0 and 6.0.1

The issue seems to occur only with certain images, for example this image worked:

https://gateway.ipfs.io/ipfs/QmXosdm4pVx2njQsSADDDTfS11sBALY6DawbVTpKU1TzZ5

Just the default camera image on an emulator, but if you use the image below (download and upload via Steemia) it won't work:

https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg 

this didn't work on the 8.0 emulator or the 6.0.1 physical device. Even if you copy and paste the URL out and try and open it in the browser it doesn't load. I assume it's an issue during upload rather than the rendering of the preview.

**Comment by hsyndeniz** [comment]
View mode works fine but IPFS does not display photos.
To resolve this issue, we should prefer **ipfs.io** endpoint instead of **gateway.ipfs.io**.
