### ISSUE TITLE
The some feature : Like, comment, upvote is not displayed when viewing post details via notification

### ISSUE THREAD

**Issue by Icramss** [Steemia/Steemia#76]
## Expected Behavior
Some features such as Liker, coment, upvote should be displayed when users view post details from notifications

## Actual Behavior
Some of these features are not displayed when users view post details through notifications

## Steps to Reproduce the Problem
- Open app
- log in with steem account
- Tap notification icon
- Tap one of your post in notification
- Scroll down to see your post.
- likes,coment,upvote feature is not displayed

## Specifications

  - Version: 6.0.1 one plus

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. Upvote and Comments are shown on the post single page. However, likers are not shown in this update. 

You stated that you cannot see them if the post is opened from notifications. However, I cannot reproduce this issue on my end. Can you please attach a video reproducing the issue? Thanks.

Also, if the mentioned features above are present except for the likers, this is mostly a suggestion instead of a bug report.

**Comment by Icramss** [comment]
Unfortunately, i able to reproduce Upvote only. I can not  see upvote  and likes . 

![20180603_034924.gif](https://cdn.steemitimages.com/DQmW1FzwbntnwV4ojmqFoYJttYP5a6hmp4Jiy8xSPqUrF5Z/20180603_034924.gif)

**Comment by jayserdny** [comment]
@Icramss Sorry but I cannot understand what are you're referring to. What do you mean by "i able to reproduce Upvote only. I can not upvote and likes "

Do you mean that you cannot see the upvotes like you do on the main screen?

**Comment by Icramss** [comment]
I said: I can only produce bugs about upvote. I can not see the apvote feature there

**Comment by jayserdny** [comment]
@Icramss I can see it in your GIF (look at the like button in the top)
