### ISSUE TITLE
Tags are not responding in the post!

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#78]
#### Expected behavior
After clicking on the tags it should show the specific tags result.

#### Actual behavior
When user click on the tags it's not showing the specific tags result and not doing anything at all.

#### How to reproduce
* Download and install Steemia from [Google play store](https://play.google.com/store/apps/details?id=com.steemia.steemia)
* Login with your Steemit account.
* Go to any post and then try to click on the tags.
* As you want to see a specific tag from a post without searching. Steemia app doesn't show any kind of result for that.
* In the recording video I've showed that how exactly it should work. It may help you understand the issue.

* App version: Steemia v0.0.4
* Operating system: Android 7.0

#### Recording Of The Bug
Apologize for the low voice quality. Please raise the volume to hear my voice. 
https://www.youtube.com/watch?v=uxBwYD3MCUg

**Comment by jayserdny** [comment]
Hello @ashiqurakash,

Thanks for your report. While this is not an issue, I will close it. This is more likely a suggestion instead of a bug: This area is not clickable by default in our app. Even though in Steemit it is possible, both are different platforms that cannot be compared each to the other. 

Filtering by tags is already developed but the update has not been sent yet. Also, even in the next update, this area is not clickable yet. Hence, it is more a suggestion than a bug report.
